// For images
export const SET_CURRENT_IMAGE_REGISTRATION = 'SET_CURRENT_IMAGE_REGISTRATION';
export const DELETE_CURRENT_IMAGE_REGISTRATION =
  'DELETE_CURRENT_IMAGE_REGISTRATION';

// For user registration
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOADING_CURRENT_USER = 'LOADING_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const ADD_CURRENT_USER_IMAGE = 'ADD_CURRENT_USER_IMAGE';
export const CLEAR_CURRENT_USER_IMAGES = 'CLEAR_CURRENT_USER_IMAGES';

// For registration status
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const REGISTRATION_RESET = 'REGISTRATION_RESET';

// For doors
export const SET_DOORS = 'SET_DOORS';
export const SET_DOORS_FAIL = 'SET_DOORS_FAIL';
export const SET_SELECTED_DOOR = 'SET_SELECTED_DOOR';

// For quotes
export const SET_QUOTES = 'SET_QUOTES';
export const ADD_QUOTE = 'ADD_QUOTE';
export const REMOVE_QUOTE = 'REMOVE_QUOTE';
